# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qtd_proto.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QMainWindow, QMdiArea,
    QMenu, QMenuBar, QSizePolicy, QStatusBar,
    QToolBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1068, 701)
        self.actionMN = QAction(MainWindow)
        self.actionMN.setObjectName(u"actionMN")
        self.actionW1 = QAction(MainWindow)
        self.actionW1.setObjectName(u"actionW1")
        self.actionD1 = QAction(MainWindow)
        self.actionD1.setObjectName(u"actionD1")
        self.actionH4 = QAction(MainWindow)
        self.actionH4.setObjectName(u"actionH4")
        self.actionH4.setCheckable(False)
        self.actionH4.setChecked(False)
        self.actionH1 = QAction(MainWindow)
        self.actionH1.setObjectName(u"actionH1")
        self.actionM30 = QAction(MainWindow)
        self.actionM30.setObjectName(u"actionM30")
        self.actionM15 = QAction(MainWindow)
        self.actionM15.setObjectName(u"actionM15")
        self.actionM15.setCheckable(False)
        self.actionM5 = QAction(MainWindow)
        self.actionM5.setObjectName(u"actionM5")
        self.actionM1 = QAction(MainWindow)
        self.actionM1.setObjectName(u"actionM1")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionTile = QAction(MainWindow)
        self.actionTile.setObjectName(u"actionTile")
        self.actionCascade = QAction(MainWindow)
        self.actionCascade.setObjectName(u"actionCascade")
        self.actionCandleChart = QAction(MainWindow)
        self.actionCandleChart.setObjectName(u"actionCandleChart")
        icon = QIcon()
        icon.addFile(u"Pyqtrader/.system/assets/candles.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCandleChart.setIcon(icon)
        self.actionBarChart = QAction(MainWindow)
        self.actionBarChart.setObjectName(u"actionBarChart")
        icon1 = QIcon()
        icon1.addFile(u"Pyqtrader/.system/assets/bar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBarChart.setIcon(icon1)
        self.actionLineChart = QAction(MainWindow)
        self.actionLineChart.setObjectName(u"actionLineChart")
        icon2 = QIcon()
        icon2.addFile(u"Pyqtrader/.system/assets/line.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLineChart.setIcon(icon2)
        self.actionDrawTrendLine = QAction(MainWindow)
        self.actionDrawTrendLine.setObjectName(u"actionDrawTrendLine")
        icon3 = QIcon()
        icon3.addFile(u"Pyqtrader/.system/assets/DrawLine.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawTrendLine.setIcon(icon3)
        self.actionDrawEllipse = QAction(MainWindow)
        self.actionDrawEllipse.setObjectName(u"actionDrawEllipse")
        icon4 = QIcon()
        icon4.addFile(u"Pyqtrader/.system/assets/ellipse.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawEllipse.setIcon(icon4)
        self.actionCrossHair = QAction(MainWindow)
        self.actionCrossHair.setObjectName(u"actionCrossHair")
        self.actionCrossHair.setCheckable(False)
        icon5 = QIcon()
        icon5.addFile(u"Pyqtrader/.system/assets/crosshair.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCrossHair.setIcon(icon5)
        self.actionDrawRectangle = QAction(MainWindow)
        self.actionDrawRectangle.setObjectName(u"actionDrawRectangle")
        icon6 = QIcon()
        icon6.addFile(u"Pyqtrader/.system/assets/rectangle.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawRectangle.setIcon(icon6)
        self.actionDrawHorLine = QAction(MainWindow)
        self.actionDrawHorLine.setObjectName(u"actionDrawHorLine")
        icon7 = QIcon()
        icon7.addFile(u"Pyqtrader/.system/assets/horizontal_line.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawHorLine.setIcon(icon7)
        self.actionDrawVerLine = QAction(MainWindow)
        self.actionDrawVerLine.setObjectName(u"actionDrawVerLine")
        icon8 = QIcon()
        icon8.addFile(u"Pyqtrader/.system/assets/vline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawVerLine.setIcon(icon8)
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        icon9 = QIcon()
        icon9.addFile(u"Pyqtrader/.system/assets/camera.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExport.setIcon(icon9)
        self.actionSymbol = QAction(MainWindow)
        self.actionSymbol.setObjectName(u"actionSymbol")
        self.actionPrice_Line = QAction(MainWindow)
        self.actionPrice_Line.setObjectName(u"actionPrice_Line")
        self.actionPrice_Line.setCheckable(False)
        self.actionDescription = QAction(MainWindow)
        self.actionDescription.setObjectName(u"actionDescription")
        self.actionTimeframe = QAction(MainWindow)
        self.actionTimeframe.setObjectName(u"actionTimeframe")
        self.actionEmpty_Profile_Bin = QAction(MainWindow)
        self.actionEmpty_Profile_Bin.setObjectName(u"actionEmpty_Profile_Bin")
        self.actionMoving_Average = QAction(MainWindow)
        self.actionMoving_Average.setObjectName(u"actionMoving_Average")
        self.actionRelative_Strength_Index = QAction(MainWindow)
        self.actionRelative_Strength_Index.setObjectName(u"actionRelative_Strength_Index")
        self.actionStochastic = QAction(MainWindow)
        self.actionStochastic.setObjectName(u"actionStochastic")
        self.actionMACD = QAction(MainWindow)
        self.actionMACD.setObjectName(u"actionMACD")
        self.actionBollinger_Bands = QAction(MainWindow)
        self.actionBollinger_Bands.setObjectName(u"actionBollinger_Bands")
        self.actionAverage_True_Range = QAction(MainWindow)
        self.actionAverage_True_Range.setObjectName(u"actionAverage_True_Range")
        self.actionDrawFibo = QAction(MainWindow)
        self.actionDrawFibo.setObjectName(u"actionDrawFibo")
        icon10 = QIcon()
        icon10.addFile(u"Pyqtrader/.system/assets/fibo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawFibo.setIcon(icon10)
        self.actionDrawFiboExt = QAction(MainWindow)
        self.actionDrawFiboExt.setObjectName(u"actionDrawFiboExt")
        icon11 = QIcon()
        icon11.addFile(u"Pyqtrader/.system/assets/fibo_ext.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawFiboExt.setIcon(icon11)
        self.actionDrawChannel = QAction(MainWindow)
        self.actionDrawChannel.setObjectName(u"actionDrawChannel")
        icon12 = QIcon()
        icon12.addFile(u"Pyqtrader/.system/assets/channel.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawChannel.setIcon(icon12)
        self.actionDrawPitchfork = QAction(MainWindow)
        self.actionDrawPitchfork.setObjectName(u"actionDrawPitchfork")
        icon13 = QIcon()
        icon13.addFile(u"Pyqtrader/.system/assets/pitchfork.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawPitchfork.setIcon(icon13)
        self.actionElliott_Impulse = QAction(MainWindow)
        self.actionElliott_Impulse.setObjectName(u"actionElliott_Impulse")
        icon14 = QIcon()
        icon14.addFile(u"Pyqtrader/.system/assets/elliott5.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionElliott_Impulse.setIcon(icon14)
        self.actionElliott_Correction = QAction(MainWindow)
        self.actionElliott_Correction.setObjectName(u"actionElliott_Correction")
        icon15 = QIcon()
        icon15.addFile(u"Pyqtrader/.system/assets/elliott3.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionElliott_Correction.setIcon(icon15)
        self.actionElliott_Extended_Correction = QAction(MainWindow)
        self.actionElliott_Extended_Correction.setObjectName(u"actionElliott_Extended_Correction")
        icon16 = QIcon()
        icon16.addFile(u"Pyqtrader/.system/assets/elliott5c.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionElliott_Extended_Correction.setIcon(icon16)
        self.actionDraw_Text = QAction(MainWindow)
        self.actionDraw_Text.setObjectName(u"actionDraw_Text")
        icon17 = QIcon()
        icon17.addFile(u"Pyqtrader/.system/assets/text.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDraw_Text.setIcon(icon17)
        self.actionDraw_Label = QAction(MainWindow)
        self.actionDraw_Label.setObjectName(u"actionDraw_Label")
        icon18 = QIcon()
        icon18.addFile(u"Pyqtrader/.system/assets/label.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDraw_Label.setIcon(icon18)
        self.actionDrawPolyline = QAction(MainWindow)
        self.actionDrawPolyline.setObjectName(u"actionDrawPolyline")
        icon19 = QIcon()
        icon19.addFile(u"Pyqtrader/.system/assets/polyline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawPolyline.setIcon(icon19)
        self.actionDrawArrow = QAction(MainWindow)
        self.actionDrawArrow.setObjectName(u"actionDrawArrow")
        icon20 = QIcon()
        icon20.addFile(u"Pyqtrader/.system/assets/arrow.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawArrow.setIcon(icon20)
        self.actionDrawPolyArrow = QAction(MainWindow)
        self.actionDrawPolyArrow.setObjectName(u"actionDrawPolyArrow")
        icon21 = QIcon()
        icon21.addFile(u"Pyqtrader/.system/assets/polyarrow.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDrawPolyArrow.setIcon(icon21)
        self.actionLogin = QAction(MainWindow)
        self.actionLogin.setObjectName(u"actionLogin")
        self.actionHistory = QAction(MainWindow)
        self.actionHistory.setObjectName(u"actionHistory")
        self.actionMagnet = QAction(MainWindow)
        self.actionMagnet.setObjectName(u"actionMagnet")
        self.actionMagnet.setCheckable(True)
        icon22 = QIcon()
        icon22.addFile(u"Pyqtrader/.system/assets/magnet.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMagnet.setIcon(icon22)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionChartProperties = QAction(MainWindow)
        self.actionChartProperties.setObjectName(u"actionChartProperties")
        self.actionGrid = QAction(MainWindow)
        self.actionGrid.setObjectName(u"actionGrid")
        self.actionRefresh = QAction(MainWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        self.actionUser_Apps = QAction(MainWindow)
        self.actionUser_Apps.setObjectName(u"actionUser_Apps")
        self.actionExperts = QAction(MainWindow)
        self.actionExperts.setObjectName(u"actionExperts")
        self.actionExperts.setCheckable(True)
        icon23 = QIcon()
        icon23.addFile(u"Pyqtrader/.system/assets/off-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        icon23.addFile(u"Pyqtrader/.system/assets/on-icon.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionExperts.setIcon(icon23)
        self.actionObjects = QAction(MainWindow)
        self.actionObjects.setObjectName(u"actionObjects")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionTabbed_View = QAction(MainWindow)
        self.actionTabbed_View.setObjectName(u"actionTabbed_View")
        self.actionTabbed_View.setCheckable(True)
        self.actionSelect_All = QAction(MainWindow)
        self.actionSelect_All.setObjectName(u"actionSelect_All")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionUndo_Delete = QAction(MainWindow)
        self.actionUndo_Delete.setObjectName(u"actionUndo_Delete")
        self.actionDeselect = QAction(MainWindow)
        self.actionDeselect.setObjectName(u"actionDeselect")
        self.actionStatus_Bar = QAction(MainWindow)
        self.actionStatus_Bar.setObjectName(u"actionStatus_Bar")
        self.actionStatus_Bar.setCheckable(True)
        self.actionStatus_Bar.setChecked(True)
        self.actionCopy_Line = QAction(MainWindow)
        self.actionCopy_Line.setObjectName(u"actionCopy_Line")
        self.actionLight_Mode = QAction(MainWindow)
        self.actionLight_Mode.setObjectName(u"actionLight_Mode")
        self.actionLight_Mode.setCheckable(True)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionLicense = QAction(MainWindow)
        self.actionLicense.setObjectName(u"actionLicense")
        self.actionOffline = QAction(MainWindow)
        self.actionOffline.setObjectName(u"actionOffline")
        self.actionOffline.setCheckable(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.mdiArea = QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(u"mdiArea")

        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1068, 23))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuChart = QMenu(self.menubar)
        self.menuChart.setObjectName(u"menuChart")
        self.menuSet_Profile = QMenu(self.menuChart)
        self.menuSet_Profile.setObjectName(u"menuSet_Profile")
        self.menuAdd_Profile = QMenu(self.menuChart)
        self.menuAdd_Profile.setObjectName(u"menuAdd_Profile")
        self.menuRemove_Profile = QMenu(self.menuChart)
        self.menuRemove_Profile.setObjectName(u"menuRemove_Profile")
        self.menuAdd_Restore_Chart_to_Profile = QMenu(self.menuChart)
        self.menuAdd_Restore_Chart_to_Profile.setObjectName(u"menuAdd_Restore_Chart_to_Profile")
        self.menuInsert = QMenu(self.menubar)
        self.menuInsert.setObjectName(u"menuInsert")
        self.menuIndicators = QMenu(self.menuInsert)
        self.menuIndicators.setObjectName(u"menuIndicators")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarForAccessories = QToolBar(MainWindow)
        self.toolBarForAccessories.setObjectName(u"toolBarForAccessories")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarForAccessories)
        self.toolBarForCharTypes = QToolBar(MainWindow)
        self.toolBarForCharTypes.setObjectName(u"toolBarForCharTypes")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarForCharTypes)
        self.tooBarForExperts = QToolBar(MainWindow)
        self.tooBarForExperts.setObjectName(u"tooBarForExperts")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.tooBarForExperts)
        self.toolBarForTimeframes = QToolBar(MainWindow)
        self.toolBarForTimeframes.setObjectName(u"toolBarForTimeframes")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarForTimeframes)
        self.toolBarForDrawings = QToolBar(MainWindow)
        self.toolBarForDrawings.setObjectName(u"toolBarForDrawings")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarForDrawings)
        self.toolBarforElliott = QToolBar(MainWindow)
        self.toolBarforElliott.setObjectName(u"toolBarforElliott")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarforElliott)
        self.toolBarforPolylines = QToolBar(MainWindow)
        self.toolBarforPolylines.setObjectName(u"toolBarforPolylines")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarforPolylines)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuChart.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionOffline)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLogin)
        self.menuWindow.addAction(self.actionTile)
        self.menuWindow.addAction(self.actionCascade)
        self.menuWindow.addAction(self.actionStatus_Bar)
        self.menuWindow.addAction(self.actionTabbed_View)
        self.menuChart.addAction(self.actionPrice_Line)
        self.menuChart.addAction(self.actionSymbol)
        self.menuChart.addAction(self.actionDescription)
        self.menuChart.addAction(self.actionTimeframe)
        self.menuChart.addAction(self.actionGrid)
        self.menuChart.addAction(self.actionRefresh)
        self.menuChart.addSeparator()
        self.menuChart.addAction(self.actionChartProperties)
        self.menuChart.addSeparator()
        self.menuChart.addAction(self.menuSet_Profile.menuAction())
        self.menuChart.addAction(self.menuAdd_Profile.menuAction())
        self.menuChart.addAction(self.menuAdd_Restore_Chart_to_Profile.menuAction())
        self.menuChart.addAction(self.menuRemove_Profile.menuAction())
        self.menuChart.addSeparator()
        self.menuChart.addAction(self.actionEmpty_Profile_Bin)
        self.menuChart.addSeparator()
        self.menuInsert.addAction(self.menuIndicators.menuAction())
        self.menuIndicators.addAction(self.actionAverage_True_Range)
        self.menuIndicators.addAction(self.actionBollinger_Bands)
        self.menuIndicators.addAction(self.actionMACD)
        self.menuIndicators.addAction(self.actionMoving_Average)
        self.menuIndicators.addAction(self.actionRelative_Strength_Index)
        self.menuIndicators.addAction(self.actionStochastic)
        self.menuTools.addAction(self.actionUser_Apps)
        self.menuTools.addAction(self.actionHistory)
        self.menuTools.addAction(self.actionSettings)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCopy_Line)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuEdit.addAction(self.actionDeselect)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionUndo_Delete)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLicense)
        self.toolBarForAccessories.addAction(self.actionCrossHair)
        self.toolBarForAccessories.addAction(self.actionExport)
        self.toolBarForAccessories.addAction(self.actionMagnet)
        self.toolBarForCharTypes.addAction(self.actionBarChart)
        self.toolBarForCharTypes.addAction(self.actionCandleChart)
        self.toolBarForCharTypes.addAction(self.actionLineChart)
        self.tooBarForExperts.addAction(self.actionExperts)
        self.toolBarForTimeframes.addAction(self.actionM1)
        self.toolBarForTimeframes.addAction(self.actionM5)
        self.toolBarForTimeframes.addAction(self.actionM15)
        self.toolBarForTimeframes.addAction(self.actionM30)
        self.toolBarForTimeframes.addAction(self.actionH1)
        self.toolBarForTimeframes.addAction(self.actionH4)
        self.toolBarForTimeframes.addAction(self.actionD1)
        self.toolBarForTimeframes.addAction(self.actionW1)
        self.toolBarForDrawings.addAction(self.actionDrawTrendLine)
        self.toolBarForDrawings.addAction(self.actionDrawHorLine)
        self.toolBarForDrawings.addAction(self.actionDrawVerLine)
        self.toolBarForDrawings.addAction(self.actionDrawChannel)
        self.toolBarForDrawings.addAction(self.actionDrawPitchfork)
        self.toolBarForDrawings.addAction(self.actionDrawFibo)
        self.toolBarForDrawings.addAction(self.actionDrawFiboExt)
        self.toolBarForDrawings.addAction(self.actionDrawEllipse)
        self.toolBarForDrawings.addAction(self.actionDrawRectangle)
        self.toolBarForDrawings.addAction(self.actionDraw_Text)
        self.toolBarForDrawings.addAction(self.actionDraw_Label)
        self.toolBarforElliott.addAction(self.actionElliott_Impulse)
        self.toolBarforElliott.addAction(self.actionElliott_Correction)
        self.toolBarforElliott.addAction(self.actionElliott_Extended_Correction)
        self.toolBarforPolylines.addAction(self.actionDrawArrow)
        self.toolBarforPolylines.addAction(self.actionDrawPolyline)
        self.toolBarforPolylines.addAction(self.actionDrawPolyArrow)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionMN.setText(QCoreApplication.translate("MainWindow", u"MN", None))
#if QT_CONFIG(tooltip)
        self.actionMN.setToolTip(QCoreApplication.translate("MainWindow", u"Monthly timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionW1.setText(QCoreApplication.translate("MainWindow", u"W", None))
#if QT_CONFIG(tooltip)
        self.actionW1.setToolTip(QCoreApplication.translate("MainWindow", u"Weekly timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionD1.setText(QCoreApplication.translate("MainWindow", u"D", None))
#if QT_CONFIG(tooltip)
        self.actionD1.setToolTip(QCoreApplication.translate("MainWindow", u"Daily timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionH4.setText(QCoreApplication.translate("MainWindow", u"H4", None))
#if QT_CONFIG(tooltip)
        self.actionH4.setToolTip(QCoreApplication.translate("MainWindow", u"4-hour timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionH1.setText(QCoreApplication.translate("MainWindow", u"H1", None))
#if QT_CONFIG(tooltip)
        self.actionH1.setToolTip(QCoreApplication.translate("MainWindow", u"Hourly timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionM30.setText(QCoreApplication.translate("MainWindow", u"M30", None))
#if QT_CONFIG(tooltip)
        self.actionM30.setToolTip(QCoreApplication.translate("MainWindow", u"30-minute timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionM15.setText(QCoreApplication.translate("MainWindow", u"M15", None))
#if QT_CONFIG(tooltip)
        self.actionM15.setToolTip(QCoreApplication.translate("MainWindow", u"15-minute timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionM5.setText(QCoreApplication.translate("MainWindow", u"M5", None))
#if QT_CONFIG(tooltip)
        self.actionM5.setToolTip(QCoreApplication.translate("MainWindow", u"5-minute timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionM1.setText(QCoreApplication.translate("MainWindow", u"M1", None))
#if QT_CONFIG(tooltip)
        self.actionM1.setToolTip(QCoreApplication.translate("MainWindow", u"1-minute timeframe", None))
#endif // QT_CONFIG(tooltip)
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionTile.setText(QCoreApplication.translate("MainWindow", u"Tile", None))
#if QT_CONFIG(shortcut)
        self.actionTile.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionCascade.setText(QCoreApplication.translate("MainWindow", u"Cascade", None))
        self.actionCandleChart.setText(QCoreApplication.translate("MainWindow", u"C", None))
#if QT_CONFIG(tooltip)
        self.actionCandleChart.setToolTip(QCoreApplication.translate("MainWindow", u"Candle chart", None))
#endif // QT_CONFIG(tooltip)
        self.actionBarChart.setText(QCoreApplication.translate("MainWindow", u"B", None))
#if QT_CONFIG(tooltip)
        self.actionBarChart.setToolTip(QCoreApplication.translate("MainWindow", u"Bar chart", None))
#endif // QT_CONFIG(tooltip)
        self.actionLineChart.setText(QCoreApplication.translate("MainWindow", u"L", None))
#if QT_CONFIG(tooltip)
        self.actionLineChart.setToolTip(QCoreApplication.translate("MainWindow", u"Line Chart", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawTrendLine.setText(QCoreApplication.translate("MainWindow", u"Li", None))
#if QT_CONFIG(tooltip)
        self.actionDrawTrendLine.setToolTip(QCoreApplication.translate("MainWindow", u"Draw Trend Line", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawEllipse.setText(QCoreApplication.translate("MainWindow", u"El", None))
#if QT_CONFIG(tooltip)
        self.actionDrawEllipse.setToolTip(QCoreApplication.translate("MainWindow", u"Draw Ellipse", None))
#endif // QT_CONFIG(tooltip)
        self.actionCrossHair.setText(QCoreApplication.translate("MainWindow", u"Ch", None))
#if QT_CONFIG(tooltip)
        self.actionCrossHair.setToolTip(QCoreApplication.translate("MainWindow", u"CrossHair; Middle-click to toggle", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionCrossHair.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionDrawRectangle.setText(QCoreApplication.translate("MainWindow", u"Re", None))
#if QT_CONFIG(tooltip)
        self.actionDrawRectangle.setToolTip(QCoreApplication.translate("MainWindow", u"Draw Rectangle", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawHorLine.setText(QCoreApplication.translate("MainWindow", u"Hl", None))
#if QT_CONFIG(tooltip)
        self.actionDrawHorLine.setToolTip(QCoreApplication.translate("MainWindow", u"Draw Horizontal Line", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawVerLine.setText(QCoreApplication.translate("MainWindow", u"Vl", None))
#if QT_CONFIG(tooltip)
        self.actionDrawVerLine.setToolTip(QCoreApplication.translate("MainWindow", u"Draw Vertical Line", None))
#endif // QT_CONFIG(tooltip)
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Ex", None))
#if QT_CONFIG(tooltip)
        self.actionExport.setToolTip(QCoreApplication.translate("MainWindow", u"Export", None))
#endif // QT_CONFIG(tooltip)
        self.actionSymbol.setText(QCoreApplication.translate("MainWindow", u"Symbol", None))
#if QT_CONFIG(tooltip)
        self.actionSymbol.setToolTip(QCoreApplication.translate("MainWindow", u"Change Symbol", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSymbol.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrice_Line.setText(QCoreApplication.translate("MainWindow", u"Price Line", None))
        self.actionDescription.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.actionTimeframe.setText(QCoreApplication.translate("MainWindow", u"Timeframe", None))
        self.actionEmpty_Profile_Bin.setText(QCoreApplication.translate("MainWindow", u"Empty Profile Bin", None))
        self.actionMoving_Average.setText(QCoreApplication.translate("MainWindow", u"Moving Average", None))
        self.actionRelative_Strength_Index.setText(QCoreApplication.translate("MainWindow", u"Relative Strength Index", None))
        self.actionStochastic.setText(QCoreApplication.translate("MainWindow", u"Stochastic", None))
        self.actionMACD.setText(QCoreApplication.translate("MainWindow", u"MACD", None))
        self.actionBollinger_Bands.setText(QCoreApplication.translate("MainWindow", u"Bollinger Bands", None))
        self.actionAverage_True_Range.setText(QCoreApplication.translate("MainWindow", u"Average True Range", None))
        self.actionDrawFibo.setText(QCoreApplication.translate("MainWindow", u"Fib", None))
#if QT_CONFIG(tooltip)
        self.actionDrawFibo.setToolTip(QCoreApplication.translate("MainWindow", u"Fibonacci", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawFiboExt.setText(QCoreApplication.translate("MainWindow", u"FibE", None))
#if QT_CONFIG(tooltip)
        self.actionDrawFiboExt.setToolTip(QCoreApplication.translate("MainWindow", u"Fibonacci Extension", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawChannel.setText(QCoreApplication.translate("MainWindow", u"Channel", None))
#if QT_CONFIG(tooltip)
        self.actionDrawChannel.setToolTip(QCoreApplication.translate("MainWindow", u"Channel", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawPitchfork.setText(QCoreApplication.translate("MainWindow", u"Pitchfork", None))
#if QT_CONFIG(tooltip)
        self.actionDrawPitchfork.setToolTip(QCoreApplication.translate("MainWindow", u"Pitchfork", None))
#endif // QT_CONFIG(tooltip)
        self.actionElliott_Impulse.setText(QCoreApplication.translate("MainWindow", u"Elliott Impulse", None))
#if QT_CONFIG(tooltip)
        self.actionElliott_Impulse.setToolTip(QCoreApplication.translate("MainWindow", u"Elliott Impulse", None))
#endif // QT_CONFIG(tooltip)
        self.actionElliott_Correction.setText(QCoreApplication.translate("MainWindow", u"Elliott Correction", None))
#if QT_CONFIG(tooltip)
        self.actionElliott_Correction.setToolTip(QCoreApplication.translate("MainWindow", u"Elliott Correction", None))
#endif // QT_CONFIG(tooltip)
        self.actionElliott_Extended_Correction.setText(QCoreApplication.translate("MainWindow", u"Elliott Extended Correction", None))
#if QT_CONFIG(tooltip)
        self.actionElliott_Extended_Correction.setToolTip(QCoreApplication.translate("MainWindow", u"Elliott Extended Correction", None))
#endif // QT_CONFIG(tooltip)
        self.actionDraw_Text.setText(QCoreApplication.translate("MainWindow", u"Draw Text", None))
#if QT_CONFIG(tooltip)
        self.actionDraw_Text.setToolTip(QCoreApplication.translate("MainWindow", u"Draw Text", None))
#endif // QT_CONFIG(tooltip)
        self.actionDraw_Label.setText(QCoreApplication.translate("MainWindow", u"Draw Label", None))
#if QT_CONFIG(tooltip)
        self.actionDraw_Label.setToolTip(QCoreApplication.translate("MainWindow", u"Draw Label", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawPolyline.setText(QCoreApplication.translate("MainWindow", u"DrawPolyline", None))
#if QT_CONFIG(tooltip)
        self.actionDrawPolyline.setToolTip(QCoreApplication.translate("MainWindow", u"Draw PolyLine; Right-click to stop", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawArrow.setText(QCoreApplication.translate("MainWindow", u"DrawArrow", None))
#if QT_CONFIG(tooltip)
        self.actionDrawArrow.setToolTip(QCoreApplication.translate("MainWindow", u"Draw Arrow", None))
#endif // QT_CONFIG(tooltip)
        self.actionDrawPolyArrow.setText(QCoreApplication.translate("MainWindow", u"DrawPolyArrow", None))
#if QT_CONFIG(tooltip)
        self.actionDrawPolyArrow.setToolTip(QCoreApplication.translate("MainWindow", u"Draw PolyArrow; Right-click to stop", None))
#endif // QT_CONFIG(tooltip)
        self.actionLogin.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.actionHistory.setText(QCoreApplication.translate("MainWindow", u"History", None))
        self.actionMagnet.setText(QCoreApplication.translate("MainWindow", u"Magnet", None))
#if QT_CONFIG(tooltip)
        self.actionMagnet.setToolTip(QCoreApplication.translate("MainWindow", u"Magnet, Alt+M", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMagnet.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+M", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
        self.actionChartProperties.setText(QCoreApplication.translate("MainWindow", u"Properties", None))
        self.actionGrid.setText(QCoreApplication.translate("MainWindow", u"Grid", None))
#if QT_CONFIG(shortcut)
        self.actionGrid.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.actionRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.actionUser_Apps.setText(QCoreApplication.translate("MainWindow", u"User Apps", None))
        self.actionExperts.setText(QCoreApplication.translate("MainWindow", u"Experts", None))
        self.actionObjects.setText(QCoreApplication.translate("MainWindow", u"Objects", None))
#if QT_CONFIG(shortcut)
        self.actionObjects.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.actionTabbed_View.setText(QCoreApplication.translate("MainWindow", u"Tabbed View", None))
        self.actionSelect_All.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
#if QT_CONFIG(shortcut)
        self.actionSelect_All.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
#if QT_CONFIG(shortcut)
        self.actionDelete.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo_Delete.setText(QCoreApplication.translate("MainWindow", u"Undo Delete", None))
#if QT_CONFIG(shortcut)
        self.actionUndo_Delete.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionDeselect.setText(QCoreApplication.translate("MainWindow", u"Deselect", None))
#if QT_CONFIG(shortcut)
        self.actionDeselect.setShortcut(QCoreApplication.translate("MainWindow", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.actionStatus_Bar.setText(QCoreApplication.translate("MainWindow", u"Status Bar", None))
        self.actionCopy_Line.setText(QCoreApplication.translate("MainWindow", u"Copy Line", None))
#if QT_CONFIG(shortcut)
        self.actionCopy_Line.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionLight_Mode.setText(QCoreApplication.translate("MainWindow", u"Light Mode", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionLicense.setText(QCoreApplication.translate("MainWindow", u"License", None))
        self.actionOffline.setText(QCoreApplication.translate("MainWindow", u"Offline", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainWindow", u"Window", None))
        self.menuChart.setTitle(QCoreApplication.translate("MainWindow", u"Chart", None))
        self.menuSet_Profile.setTitle(QCoreApplication.translate("MainWindow", u"Set Profile", None))
        self.menuAdd_Profile.setTitle(QCoreApplication.translate("MainWindow", u"Add Profile", None))
        self.menuRemove_Profile.setTitle(QCoreApplication.translate("MainWindow", u"Remove Profile", None))
        self.menuAdd_Restore_Chart_to_Profile.setTitle(QCoreApplication.translate("MainWindow", u"Add/Restore Chart to Profile", None))
        self.menuInsert.setTitle(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.menuIndicators.setTitle(QCoreApplication.translate("MainWindow", u"Indicators", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBarForAccessories.setWindowTitle(QCoreApplication.translate("MainWindow", u"Accessories", None))
        self.toolBarForCharTypes.setWindowTitle(QCoreApplication.translate("MainWindow", u"Chart Types", None))
        self.tooBarForExperts.setWindowTitle(QCoreApplication.translate("MainWindow", u"Experts", None))
        self.toolBarForTimeframes.setWindowTitle(QCoreApplication.translate("MainWindow", u"Timeframes", None))
        self.toolBarForDrawings.setWindowTitle(QCoreApplication.translate("MainWindow", u"Drawings", None))
        self.toolBarforElliott.setWindowTitle(QCoreApplication.translate("MainWindow", u"Elliott", None))
        self.toolBarforPolylines.setWindowTitle(QCoreApplication.translate("MainWindow", u"Polylines", None))
    # retranslateUi

